- js-timezone-selector-plugin/package.json
> Added exports

- js-timezone-selector-plugin/vite.config.ts
> Updated vite config

- js-timezone-selector-plugin/src/selector/index.tsx
> Added callback to get the selected value

- js-timezone-selector-plugin/package.json
> Fixed package.json

- js-timezone-selector-plugin/package-lock.json
- js-timezone-selector-plugin/package.json
- js-timezone-selector-plugin/pnpm-lock.yaml
- js-timezone-selector-plugin/postcss.config.js
- js-timezone-selector-plugin/src/styles.css
> Fix tailwind configurations

- js-timezone-selector-plugin/src/selector/Button.jsx
- js-timezone-selector-plugin/src/selector/Options.jsx
- js-timezone-selector-plugin/src/selector/OptionsContainer.jsx
- js-timezone-selector-plugin/src/selector/Search/index.jsx
- js-timezone-selector-plugin/src/selector/utils.jsx
> UI updates

- js-timezone-selector-plugin/src/selector/index.tsx
> Fixed cannot-read-properties-of-null-reading-contains

- js-timezone-selector-plugin/src/selector/Button.jsx
- js-timezone-selector-plugin/src/selector/Options.jsx
- js-timezone-selector-plugin/src/selector/OptionsContainer.jsx
- js-timezone-selector-plugin/src/selector/Search/index.jsx
- js-timezone-selector-plugin/src/selector/index.tsx
> Removed onClick listener on unmount and added dynamic element id

- .vscode/settings.json
- js-timezone-selector-plugin/.eslintignore
- js-timezone-selector-plugin/.eslintrc.json
- js-timezone-selector-plugin/package.json
- js-timezone-selector-plugin/pnpm-lock.yaml
- js-timezone-selector-plugin/postcss.config.js
- js-timezone-selector-plugin/src/dev.ts
- js-timezone-selector-plugin/src/main.tsx
- js-timezone-selector-plugin/src/selector/Search/utils.js
- js-timezone-selector-plugin/src/selector/index.tsx
- js-timezone-selector-plugin/tailwind.config.js
- js-timezone-selector-plugin/vite.config.ts
> Fixes eslint and autoformatter

- js/timezone-selector-plugin/selector/index.tsx
> Fixed document.getElementById(...) is null error

- js/timezone-selector-plugin/css/styles.css
- js/timezone-selector-plugin/selector/Button.jsx
- js/timezone-selector-plugin/selector/Options.jsx
- js/timezone-selector-plugin/selector/utils.jsx
> Added indicator for DST

- README.md
- js/README.md
> Added readme

- js/ianaTimezoneToHumanReadable/index.js
- js/package.json
> Fixed ianaTimezoneToHumanReadable function

- data/africa.json
- data/america.json
- data/asia.json
- data/atlantic.json
- data/australia.json
- data/europe.json
- data/pacific.json
- data/us_canada.json
- js/timezone-selector-plugin/selector/Button.jsx
- js/timezone-selector-plugin/selector/Options.jsx
- js/timezone-selector-plugin/selector/Search/utils.js
- js/timezone-selector-plugin/selector/utils.jsx
> Cleanup json files

- data/europe.json
- data/us_canada.json
- js/package.json
- js/timezone-selector-plugin/css/styles.css
- js/timezone-selector-plugin/selector/Button.jsx
- js/timezone-selector-plugin/selector/commons/Button.jsx
- js/timezone-selector-plugin/selector/utils.jsx
> Refactoring and UI enhancements

- data/australia.json
> Added missing data

- js/package.json
- js/timezone-selector-plugin/selector/commons/Button.jsx
> Text change

- js/timezone-selector-plugin/selector/Options.jsx
- js/timezone-selector-plugin/selector/OptionsContainer.jsx
> Scroll container to the top on search input

- data/africa.json
- data/america.json
- data/asia.json
- data/atlantic.json
- data/australia.json
- data/europe.json
- data/pacific.json
- data/us_canada.json
- js/timezone-selector-plugin/selector/commons/Button.jsx
> Keyword fixes

- data/us_canada.json
> Updated US_Canada json file

- js/package.json
- js/timezone-selector-plugin/css/styles.css
- js/timezone-selector-plugin/selector/Button.jsx
- js/timezone-selector-plugin/selector/Options.jsx
- js/timezone-selector-plugin/selector/OptionsContainer.jsx
- js/timezone-selector-plugin/selector/commons/Button.jsx
- js/timezone-selector-plugin/selector/commons/Switch.jsx
- js/timezone-selector-plugin/selector/commons/utils.js
- js/timezone-selector-plugin/selector/index.tsx
- js/timezone-selector-plugin/selector/utils.jsx
> Add a 24h time format switch button

- js/README.md
- js/package.json
- js/timezone-selector-plugin/selector/index.tsx
> Added callback function onHourFormatChange

- js/package.json
> Updated package.json

- js/package.json
- js/vite.config.ts
> Added cjs module

- .vscode/settings.json
- data/europe.json
- js/index.html
- js/timezone-selector-plugin/selector/OptionsContainer.jsx
- js/timezone-selector-plugin/selector/Search/utils.js
- js/timezone-selector-plugin/selector/commons/Button.jsx
- js/timezone-selector-plugin/selector/commons/Switch.jsx
> Fix european timezones
